
default: &default

  adapter: postgresql
  encoding: unicode
  pool: 5
  username: postgres
  password: 123  # Đảm bảo mật khẩu đúng với mật khẩu PostgreSQL của bạn
  host: localhost
  port: 5432

development:
  <<: *default
  database: postgres  # Dùng cơ sở dữ liệu postgres cho development


test:
  <<: *default
  database: postgres  # Dùng cơ sở dữ liệu postgres cho test
production:

  <<: *default
  database: postgres  # Dùng cơ sở dữ liệu postgres cho production
  username: shop      # Nếu cần thiết, có thể thay đổi username
  password: <%= ENV['SHOP_DATABASE_PASSWORD'] %>  # Nếu có biến môi trường cho password
  host: <%= ENV['DATABASE_HOST'] %>
